### ISSUE TITLE
(Windows) Does it need sed? If so, what environment variable to set it to?

### ISSUE THREAD

**Issue by niwrA** [meltedspark/electron-angular2-native#1]
> @ install E:\Samples\Electron\electron-angular2-native
> node-gyp rebuild

E:\Samples\Electron\electron-angular2-native>if not defined npm_config_node_gyp (node "E:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
'sed' is not recognized as an internal or external command,
operable program or batch file.
gyp: Call to 'find app/plugins/native -not -path "./**/node_modules/*" -mindepth 2 -name binding.gyp | sed -e s/$/:*/' returned exit status 255. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (E:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:355:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.14393

**Comment by meltedspark** [comment]
You should use bash shell (which generally comes with sed). I personally
use git-bash for this. Just run the npm install from git-bash and it will
work.
